// GENERATED by scripts/gen-tools.mjs from the local OpenAPI document — do not edit.
// Regenerate with `npm run gen` after the Glasser contract changes.
import type { JsonSchema } from "@paperclipai/plugin-sdk";

export const SOLUTION = "gtm";

export interface ToolSpec {
  readonly name: string;
  readonly displayName: string;
  readonly description: string;
  readonly parametersSchema: JsonSchema;
  /** Fields the contract types as arrays; a comma-separated string is accepted and split. */
  readonly lists: readonly string[];
  /** Fields the contract types as numbers; a numeric string is accepted and parsed. */
  readonly integers: readonly string[];
}

export const TOOLS: readonly ToolSpec[] = [
  {
    "name": "web_research",
    "displayName": "Web Research",
    "description": "Search the web, news and places, read a page's content, or get an answer with sources. Actions search, news, places, scholar, shopping, images, videos and answer take query; scrape and similar take url. Providers: Serper, SerpApi, Exa, DataForSEO. Routes to one Endpoint per action; provider auto picks the first preferred Provider this key may run, a named provider forces it. The response is exactly the Run that POST /v1/runs returns — provider-native output, exact charge_usd, run_url; its provider, endpoint and input say which Endpoint served the call. Under auto, a Provider error, timeout or rate limit falls back to the next preferred Provider; a no-result answer does not. Each fallback hop is its own Run, visible in the runs list. Idempotency-Key is required and behaves exactly as on POST /v1/runs.",
    "parametersSchema": {
      "type": "object",
      "properties": {
        "action": {
          "type": "string",
          "enum": [
            "search",
            "news",
            "places",
            "scholar",
            "shopping",
            "images",
            "videos",
            "answer",
            "scrape",
            "similar"
          ],
          "description": "Default search. search, news, places, scholar, shopping, images, videos and answer take query; scrape and similar take url."
        },
        "provider": {
          "type": "string",
          "enum": [
            "auto",
            "serper",
            "serpapi",
            "exa",
            "dataforseo"
          ],
          "description": "Data provider: auto (default) or one of serper, serpapi, exa, dataforseo. Name one only when the caller asks for that vendor."
        },
        "query": {
          "type": "string",
          "description": "Search phrase or question."
        },
        "url": {
          "type": "string",
          "description": "A full http(s) URL."
        },
        "country": {
          "type": "string",
          "description": "Country for search-type actions, as a two-letter ISO code or a country name. Default us. Not for scrape or similar. Refused with 400 when the named provider cannot apply it."
        },
        "limit": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100,
          "description": "Rows to return. Keep it small: the routed Endpoint's charge rule may read it. Each capability caps it further."
        }
      },
      "required": [],
      "additionalProperties": false
    },
    "lists": [],
    "integers": [
      "limit"
    ]
  },
  {
    "name": "company_intelligence",
    "displayName": "Company Intelligence",
    "description": "From a domain, get the company profile and firmographics, technology stack, website traffic, similar companies, funding rounds or news. Providers: Apollo, People Data Labs, Hunter, Prospeo, PredictLeads, LeadMagic, BuiltWith, DataForSEO, Ahrefs, Apify, Exa, Serper. Routes to one Endpoint per action; provider auto picks the first preferred Provider this key may run, a named provider forces it. The response is exactly the Run that POST /v1/runs returns — provider-native output, exact charge_usd, run_url; its provider, endpoint and input say which Endpoint served the call. Under auto, a Provider error, timeout or rate limit falls back to the next preferred Provider; a no-result answer does not. Each fallback hop is its own Run, visible in the runs list. Idempotency-Key is required and behaves exactly as on POST /v1/runs.",
    "parametersSchema": {
      "type": "object",
      "properties": {
        "action": {
          "type": "string",
          "enum": [
            "enrich",
            "tech_stack",
            "traffic",
            "competitors",
            "funding",
            "news"
          ],
          "description": "Default enrich. enrich: profile and firmographics; tech_stack; traffic; competitors: businesses similar to the company (for the domains it competes with in Google results use seo_research organic_competitors); funding; news. All take domain."
        },
        "provider": {
          "type": "string",
          "enum": [
            "auto",
            "apollo",
            "pdl",
            "hunter",
            "prospeo",
            "predictleads",
            "leadmagic",
            "builtwith",
            "dataforseo",
            "ahrefs",
            "apify",
            "exa",
            "serper"
          ],
          "description": "Data provider: auto (default) or one of apollo, pdl, hunter, prospeo, predictleads, leadmagic, builtwith, dataforseo, ahrefs, apify, exa, serper. Name one only when the caller asks for that vendor."
        },
        "domain": {
          "type": "string",
          "description": "A website domain such as stripe.com. A full URL is accepted and reduced to its host."
        },
        "country": {
          "type": "string",
          "description": "Country as a two-letter ISO code or a country name, e.g. us, gb, de, Germany. Default us. An unsupported country is refused with the supported list."
        },
        "limit": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100,
          "description": "Rows to return. Keep it small: the routed Endpoint's charge rule may read it. Each capability caps it further."
        }
      },
      "required": [
        "domain"
      ],
      "additionalProperties": false
    },
    "lists": [],
    "integers": [
      "limit"
    ]
  },
  {
    "name": "people_search",
    "displayName": "People Search",
    "description": "Find contacts by title, seniority, location or employer, enrich one person's profile, or find a work email. Providers: Apollo, People Data Labs, LeadMagic, ZoomInfo, Hunter, Prospeo. Routes to one Endpoint per action; provider auto picks the first preferred Provider this key may run, a named provider forces it. The response is exactly the Run that POST /v1/runs returns — provider-native output, exact charge_usd, run_url; its provider, endpoint and input say which Endpoint served the call. Under auto, a Provider error, timeout or rate limit falls back to the next preferred Provider; a no-result answer does not. Each fallback hop is its own Run, visible in the runs list. Idempotency-Key is required and behaves exactly as on POST /v1/runs.",
    "parametersSchema": {
      "type": "object",
      "properties": {
        "action": {
          "type": "string",
          "enum": [
            "search",
            "enrich",
            "find_email"
          ],
          "description": "Default search. search: people matching job_titles, seniorities, locations, company_domain or keywords (at least one); a filter is never silently dropped — under auto a Provider that cannot apply one of the given filters is skipped, a named Provider that cannot is refused with 400. enrich: one person from linkedin_url, email, or full_name plus company_domain. find_email: the work email of full_name at company_domain."
        },
        "provider": {
          "type": "string",
          "enum": [
            "auto",
            "apollo",
            "pdl",
            "leadmagic",
            "zoominfo",
            "hunter",
            "prospeo"
          ],
          "description": "Data provider: auto (default) or one of apollo, pdl, leadmagic, zoominfo, hunter, prospeo. Name one only when the caller asks for that vendor."
        },
        "job_titles": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Job titles, e.g. ['CTO', 'VP Engineering']."
        },
        "seniorities": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Seniority levels, one or more of owner, founder, c_suite, partner, vp, head, director, manager, senior, entry, intern."
        },
        "locations": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Cities, states or countries."
        },
        "company_domain": {
          "type": "string",
          "description": "A website domain such as stripe.com. A full URL is accepted and reduced to its host."
        },
        "full_name": {
          "type": "string",
          "description": "The person's full name, e.g. 'Patrick Collison'."
        },
        "email": {
          "type": "string",
          "description": "An email address."
        },
        "linkedin_url": {
          "type": "string",
          "description": "The person's LinkedIn profile URL, linkedin.com/in/<slug>. Not a company page."
        },
        "limit": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100,
          "description": "Rows to return. Keep it small: the routed Endpoint's charge rule may read it. Each capability caps it further."
        }
      },
      "required": [],
      "additionalProperties": false
    },
    "lists": [
      "job_titles",
      "seniorities",
      "locations"
    ],
    "integers": [
      "limit"
    ]
  },
  {
    "name": "seo_research",
    "displayName": "SEO Research",
    "description": "Keyword volume and difficulty, keyword ideas, Google results for a keyword, a domain's organic overview, ranking keywords and organic competitors, backlink totals and rows, referring domains, domain rating. Providers: Semrush, Serpstat, DataForSEO, Ahrefs, Serper. Routes to one Endpoint per action; provider auto picks the first preferred Provider this key may run, a named provider forces it. The response is exactly the Run that POST /v1/runs returns — provider-native output, exact charge_usd, run_url; its provider, endpoint and input say which Endpoint served the call. Under auto, a Provider error, timeout or rate limit falls back to the next preferred Provider; a no-result answer does not. Each fallback hop is its own Run, visible in the runs list. Idempotency-Key is required and behaves exactly as on POST /v1/runs.",
    "parametersSchema": {
      "type": "object",
      "properties": {
        "action": {
          "type": "string",
          "enum": [
            "keyword_overview",
            "keyword_ideas",
            "serp",
            "domain_overview",
            "ranked_keywords",
            "organic_competitors",
            "backlinks_overview",
            "backlinks",
            "referring_domains",
            "domain_rating"
          ],
          "description": "Default keyword_overview. keyword_overview takes keywords (several at once); keyword_ideas and serp take exactly one keyword in keywords; domain_overview, ranked_keywords, organic_competitors (domains ranking for the same keywords), backlinks_overview, backlinks, referring_domains and domain_rating take domain."
        },
        "provider": {
          "type": "string",
          "enum": [
            "auto",
            "semrush",
            "serpstat",
            "dataforseo",
            "ahrefs",
            "serper"
          ],
          "description": "Data provider: auto (default) or one of semrush, serpstat, dataforseo, ahrefs, serper. Name one only when the caller asks for that vendor."
        },
        "keywords": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Keywords to look up, e.g. ['espresso machine']."
        },
        "domain": {
          "type": "string",
          "description": "A website domain such as stripe.com. A full URL is accepted and reduced to its host."
        },
        "country": {
          "type": "string",
          "description": "Country as a two-letter ISO code or a country name, e.g. us, gb, de, Germany. Default us. An unsupported country is refused with the supported list."
        },
        "limit": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100,
          "description": "Rows to return. Keep it small: the routed Endpoint's charge rule may read it. Each capability caps it further."
        }
      },
      "required": [],
      "additionalProperties": false
    },
    "lists": [
      "keywords"
    ],
    "integers": [
      "limit"
    ]
  },
  {
    "name": "social_research",
    "displayName": "Social Media Research",
    "description": "Search posts, read a profile or channel, fetch one post, or find an account's other profiles on Reddit, X, YouTube, TikTok, Instagram and LinkedIn. Read-only. Takes platform and mode instead of action; every platform supports every mode. Providers: ScrapeCreators, Apify, TikHub, People Data Labs. Routes to one Endpoint per action; provider auto picks the first preferred Provider this key may run, a named provider forces it. The response is exactly the Run that POST /v1/runs returns — provider-native output, exact charge_usd, run_url; its provider, endpoint and input say which Endpoint served the call. Under auto, a Provider error, timeout or rate limit falls back to the next preferred Provider; a no-result answer does not. Each fallback hop is its own Run, visible in the runs list. Idempotency-Key is required and behaves exactly as on POST /v1/runs.",
    "parametersSchema": {
      "type": "object",
      "properties": {
        "platform": {
          "type": "string",
          "enum": [
            "reddit",
            "x",
            "youtube",
            "tiktok",
            "instagram",
            "linkedin"
          ]
        },
        "mode": {
          "type": "string",
          "enum": [
            "search",
            "profile",
            "feed",
            "post",
            "find"
          ],
          "description": "Default search. search: posts matching query. profile: the account itself — bio, follower counts, links — from handle (reddit: the subreddit; linkedin: url of a person's profile or a company page). feed: the account's recent posts or videos, from handle (linkedin: url of a company page). post: one post or video from url. find: an account's other social profiles, from handle (linkedin: url of a person's profile; reddit: subreddits matching query). Every platform supports every mode."
        },
        "provider": {
          "type": "string",
          "enum": [
            "auto",
            "scrapecreators",
            "apify",
            "tikhub",
            "pdl"
          ],
          "description": "Data provider: auto (default) or one of scrapecreators, apify, tikhub, pdl. Name one only when the caller asks for that vendor."
        },
        "query": {
          "type": "string",
          "description": "Search phrase or question."
        },
        "handle": {
          "type": "string",
          "description": "A username without @, or a subreddit name without r/."
        },
        "url": {
          "type": "string",
          "description": "A full http(s) URL."
        }
      },
      "required": [
        "platform"
      ],
      "additionalProperties": false
    },
    "lists": [],
    "integers": []
  },
  {
    "name": "market_data",
    "displayName": "US Market Data",
    "description": "US property values, rent estimates, property records, for-sale and rental listings, ZIP-code market statistics, and stock quotes. Providers: RentCast, SerpApi. Routes to one Endpoint per action; provider auto picks the first preferred Provider this key may run, a named provider forces it. The response is exactly the Run that POST /v1/runs returns — provider-native output, exact charge_usd, run_url; its provider, endpoint and input say which Endpoint served the call. Under auto, a Provider error, timeout or rate limit falls back to the next preferred Provider; a no-result answer does not. Each fallback hop is its own Run, visible in the runs list. Idempotency-Key is required and behaves exactly as on POST /v1/runs.",
    "parametersSchema": {
      "type": "object",
      "properties": {
        "action": {
          "type": "string",
          "enum": [
            "property_value",
            "property_rent",
            "property_search",
            "listings_sale",
            "listings_rental",
            "market_stats",
            "stock_quote"
          ],
          "description": "property_value and property_rent take address. property_search, listings_sale and listings_rental take address, or city plus state, or zip. market_stats takes zip. stock_quote takes symbol."
        },
        "provider": {
          "type": "string",
          "enum": [
            "auto",
            "rentcast",
            "serpapi"
          ],
          "description": "Data provider: auto (default) or one of rentcast, serpapi. Name one only when the caller asks for that vendor."
        },
        "address": {
          "type": "string",
          "description": "US street address, e.g. '5500 Grand Lake Dr, San Antonio, TX 78244'."
        },
        "city": {
          "type": "string",
          "description": "US city name; use with state."
        },
        "state": {
          "type": "string",
          "description": "Two-letter US state code, e.g. TX."
        },
        "zip": {
          "type": "string",
          "description": "Five-digit US ZIP code."
        },
        "symbol": {
          "type": "string",
          "description": "Ticker with exchange, e.g. AAPL:NASDAQ."
        },
        "limit": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100,
          "description": "Rows to return. Keep it small: the routed Endpoint's charge rule may read it. Each capability caps it further."
        }
      },
      "required": [
        "action"
      ],
      "additionalProperties": false
    },
    "lists": [],
    "integers": [
      "limit"
    ]
  }
];
